seed: 42
data:
  path: data/framingham_sample.csv
  target: TenYearCHD
  numeric: [age, cigsPerDay, totChol, sysBP, diaBP, BMI, heartRate, glucose]
  categorical: [male, education, currentSmoker, BPMeds, prevalentStroke, prevalentHyp, diabetes]
missingness:
  types: [MCAR, MAR, MNAR]
  fractions: [0.1, 0.2, 0.3]
evaluation:
  downstream_model: logistic
  sensitivity_deltas: [-0.05, 0.0, 0.05]
llm:
  enabled: true
  confidence_threshold: 0.70
  validation_min_pass: 0.95
  probe_size: 50
output:
  dir: results
